In [5]:
import pandas as pd
matches = pd.read_csv("ddedication.csv", index_col = 0)
matches.head()

,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes,Season
0,Liverpool,16,11,4,1,36,15,21,37,2.31,32.1,19.7,12.4,0.77,W D W W W,50573,Mohamed Salah - 11,Alisson,NaN,2023
1,Arsenal,16,11,3,2,33,15,18,36,2.25,29.0,12.1,16.9,1.06,W W W W L,60147,"Eddie Nketiah, Bukayo Saka - 5",David Raya,NaN,2023
2,Aston Villa,16,11,2,3,35,20,15,35,2.19,28.8,22.2,6.6,0.41,W W D W W,36211,Ollie Watkins - 8,Emiliano Martínez,NaN,2023
3,Manchester City,16,10,3,3,38,18,20,33,2.06,30.6,14.7,15.8,0.99,D D D L W,45700,Erling Haaland - 14,Ederson,NaN,2023
4,Tottenham,16,9,3,4,33,23,10,30,1.88,27.6,26.8,0.8,0.05,L L D L W,53935,Son Heung-min - 10,Guglielmo Vicario,NaN,2023

In [7]:
matches["Squad"].value_counts()

Squad
Liverpool          3
West Ham           3
Everton            3
Crystal Palace     3
Arsenal            3
Chelsea            3
Brentford          3
Wolves             3
Brighton           3
Tottenham          3
Manchester City    3
Aston Villa        3
Manchester Utd     3
Newcastle Utd      3
Bournemouth        2
Nott'ham Forest    2
Fulham             2
Burnley            2
Leicester City     2
Leeds United       2
Southampton        2
Luton Town         1
Sheffield Utd      1
Watford            1
Norwich City       1
Name: count, dtype: int64